import React from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import {
  faGaugeHigh,
  faBolt,
  faSun,
  faBatteryFull,
  faBatteryThreeQuarters,
  faBatteryHalf,
  faBatteryQuarter,
  faBatteryEmpty,
  faStore,
  faHandshake,
  faCartShopping,
  faCoins,
  faIndianRupeeSign,
  faArrowRightArrowLeft,
  faBrain,
  faWandMagicSparkles,
  faRobot,
  faMicrochip,
  faLightbulb,
  faWifi,
  faServer,
  faNetworkWired,
  faSignal,
  faHouse,
  faBuilding,
  faTemperatureHalf,
  faTv,
  faFan,
  faCar,
  faCarSide,
  faReceipt,
  faFileInvoice,
  faListCheck,
  faHistory,
  faFileArrowDown,
  faCircleCheck,
  faCircleExclamation,
  faTriangleExclamation,
  faCircleXmark,
  faRotate,
  faPlay,
  faPause,
  faArrowRight,
  faArrowUpRightFromSquare,
  faChevronRight,
  faChevronLeft,
  faSliders,
  faShieldHalved,
  faEye,
  faFilter,
  faMagnifyingGlass,
  faClock,
  faInfoCircle,
  faChartLine,
  faChartPie,
  faPowerOff,
  faPlug,
  faTowerBroadcast,
  faChargingStation,
  faGear,
  faUsers,
  faBell,
  faCheck,
  faXmark,
  faArrowUp,
  faArrowDown,
  faCloudSun,
  faMoon,
  faLeaf,
} from '@fortawesome/free-solid-svg-icons';

export const ICONS = {
  // Navigation & Core Domains
  overview: faGaugeHigh,
  dashboard: faGaugeHigh,
  network: faNetworkWired,
  energy: faBolt,
  power: faBolt,
  solar: faSun,
  battery: faBatteryThreeQuarters,
  batteryFull: faBatteryFull,
  batteryHalf: faBatteryHalf,
  batteryQuarter: faBatteryQuarter,
  batteryEmpty: faBatteryEmpty,
  charging: faChargingStation,
  marketplace: faStore,
  trade: faHandshake,
  cart: faCartShopping,
  p2p: faArrowRightArrowLeft,
  ai: faBrain,
  copilot: faBrain,
  sparkles: faWandMagicSparkles,
  robot: faRobot,
  devices: faMicrochip,
  microchip: faMicrochip,
  wifi: faWifi,
  server: faServer,
  home: faHouse,
  building: faBuilding,
  transactions: faReceipt,
  receipt: faReceipt,
  invoice: faFileInvoice,
  history: faHistory,
  export: faFileArrowDown,
  grid: faTowerBroadcast,
  plug: faPlug,
  
  // Status & Feedback
  check: faCheck,
  checkCircle: faCircleCheck,
  success: faCircleCheck,
  warning: faTriangleExclamation,
  danger: faCircleXmark,
  error: faCircleXmark,
  info: faInfoCircle,
  alert: faBell,
  shield: faShieldHalved,
  refresh: faRotate,
  rotate: faRotate,
  play: faPlay,
  pause: faPause,
  sliders: faSliders,
  settings: faGear,
  users: faUsers,
  filter: faFilter,
  search: faMagnifyingGlass,
  view: faEye,
  clock: faClock,
  analytics: faChartLine,
  chart: faChartPie,
  powerOff: faPowerOff,
  rupee: faIndianRupeeSign,
  coins: faCoins,
  leaf: faLeaf,
  cloudSun: faCloudSun,
  moon: faMoon,
  
  // Directional
  arrowRight: faArrowRight,
  arrowUpRight: faArrowUpRightFromSquare,
  arrowUp: faArrowUp,
  arrowDown: faArrowDown,
  chevronRight: faChevronRight,
  chevronLeft: faChevronLeft,
  close: faXmark,
};

export default function FaIcon({
  name,
  icon,
  className = '',
  size,
  color,
  spin = false,
  title,
  ariaLabel,
  ...props
}) {
  const resolvedIcon = icon || (name ? ICONS[name] : null) || faBolt;

  return (
    <FontAwesomeIcon
      icon={resolvedIcon}
      className={className}
      size={size}
      color={color}
      spin={spin}
      title={title}
      aria-label={ariaLabel || title}
      {...props}
    />
  );
}
