import {
  faGaugeHigh,
  faBolt,
  faBrain,
  faStore,
  faBatteryThreeQuarters,
  faHouse,
  faMicrochip,
  faReceipt,
  faChartLine,
  faWandMagicSparkles,
  faServer,
  faHeartPulse,
  faGear,
  faBell,
  faUser,
  faChevronLeft,
  faChevronRight,
  faChevronDown,
  faChevronUp,
  faEllipsis,
  faCompress,
  faExpand,
  faSliders,
  faSun,
  faTowerBroadcast,
  faUsers,
  faCheck,
  faCircleCheck,
  faCircleExclamation,
  faTriangleExclamation,
  faCircleXmark,
  faRotate,
  faPlay,
  faPause,
  faXmark,
  faBars,
  faArrowRight,
  faArrowUp,
  faArrowDown,
  faChargingStation,
  faPlug,
  faLightbulb,
  faIndianRupeeSign,
  faLeaf,
  faShieldHalved,
  faTv,
  faFan,
  faCar,
} from '@fortawesome/free-solid-svg-icons';

export const ICON_REGISTRY = {
  // Navigation
  overview: faGaugeHigh,
  network: faBolt,
  energy: faBolt,
  ai: faBrain,
  copilot: faBrain,
  marketplace: faStore,
  battery: faBatteryThreeQuarters,
  home: faHouse,
  devices: faMicrochip,
  transactions: faReceipt,
  analytics: faChartLine,
  scenarios: faWandMagicSparkles,
  health: faHeartPulse,
  server: faServer,
  settings: faGear,
  
  // Utilities
  notifications: faBell,
  alert: faBell,
  profile: faUser,
  user: faUser,
  users: faUsers,
  solar: faSun,
  grid: faTowerBroadcast,
  charging: faChargingStation,
  plug: faPlug,
  lightbulb: faLightbulb,
  rupee: faIndianRupeeSign,
  leaf: faLeaf,
  shield: faShieldHalved,
  tv: faTv,
  fan: faFan,
  ev: faCar,
  car: faCar,
  trade: faStore,
  camera: faGaugeHigh,
  
  // Controls & Actions
  chevronLeft: faChevronLeft,
  chevronRight: faChevronRight,
  chevronDown: faChevronDown,
  chevronUp: faChevronUp,
  ellipsis: faEllipsis,
  compress: faCompress,
  expand: faExpand,
  sliders: faSliders,
  bars: faBars,
  close: faXmark,
  check: faCheck,
  checkCircle: faCircleCheck,
  warning: faTriangleExclamation,
  error: faCircleXmark,
  rotate: faRotate,
  refresh: faRotate,
  play: faPlay,
  pause: faPause,
  arrowRight: faArrowRight,
  arrowUp: faArrowUp,
  arrowDown: faArrowDown,
  sparkles: faWandMagicSparkles,
};

export const getIcon = (name) => {
  return ICON_REGISTRY[name] || faBolt;
};
